---
swagger: "2.0"
info:
  description: "Esta aplicación ha sido desarrollada para explotar la información\
    \ de sensores presente el robot de nuestra empresa"
  version: "1.0.0"
  title: "Robot industry - Sensores"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "nanana@hotmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/v2"
tags:
- name: "Sensores"
  description: "Información relacionada con los Sensores"
schemes:
- "https"
- "http"
paths:
  /getHistoricalMeassuresBySensorAndType/{sensor}/{start}/{end}:
    get:
      tags:
      - "Sensores"
      summary: "Obtener la última medición de un sensor"
      description: "Recuperar la última medición de un sensor"
      operationId: "get_historical_meassures_by_sensor_and_type"
      consumes:
      - "application/xml"
      produces:
      - "application/json"
      parameters:
      - name: "sensor"
        in: "path"
        description: "ID del sensor"
        required: true
        type: "string"
      - name: "start"
        in: "path"
        description: "Fecha de inicio miliseconds"
        required: true
        type: "string"
      - name: "end"
        in: "path"
        description: "Fecha de fin miliseconds"
        required: true
        type: "string"
      responses:
        "200":
          description: "Medicion encontrada"
          schema:
            $ref: "#/definitions/Meassure"
        default:
          description: "Invalid  order"
          schema:
            $ref: "#/definitions/Message"
      x-codegen-request-body-name: "body"
      x-openapi-router-controller: "swagger_server.controllers.sensores_controller"
      x-swagger-router-controller: "swagger_server.controllers.sensores_controller"
  /getLastMeassureBySensor/{sensor}:
    get:
      tags:
      - "Sensores"
      summary: "Obtener la última medición de un sensor"
      description: "Recuperar la última medición de un sensor"
      operationId: "get_last_meassure_by_sensor"
      consumes:
      - "application/xml"
      produces:
      - "application/json"
      parameters:
      - name: "sensor"
        in: "path"
        description: "ID del sensor"
        required: true
        type: "string"
      responses:
        "200":
          description: "Medicion encontrada"
          schema:
            $ref: "#/definitions/Meassure"
        default:
          description: "Invalid  order"
          schema:
            $ref: "#/definitions/Message"
      x-codegen-request-body-name: "body"
      x-openapi-router-controller: "swagger_server.controllers.sensores_controller"
      x-swagger-router-controller: "swagger_server.controllers.sensores_controller"
definitions:
  Meassure:
    type: "object"
    required:
    - "code"
    - "fechamuestreo"
    - "medicion"
    - "tipo"
    - "unidad"
    properties:
      code:
        type: "string"
      fechamuestreo:
        type: "string"
      unidad:
        type: "string"
      tipo:
        type: "string"
      medicion:
        type: "number"
    example:
      unidad: "unidad"
      tipo: "tipo"
      medicion: 0.80082819046101150206595775671303272247314453125
      code: "code"
      fechamuestreo: "fechamuestreo"
  Message:
    type: "object"
    required:
    - "code"
    - "message"
    properties:
      code:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
