FROM alpine

# Creating the folder
RUN mkdir ejercicio1  
# adding ejercicio1.txt to the folder
RUN touch ejercicio1/ejercicio1.txt
# writting into ejercicio1.txt
RUN echo 'Ejercicio 1' > ejercicio1/ejercicio1.txt

CMD [ "echo" , "He acabado el ejercicio 1" ]