# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Meassure(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, code: str=None, fechamuestreo: str=None, unidad: str=None, tipo: str=None, medicion: float=None):  # noqa: E501
        """Meassure - a model defined in Swagger

        :param code: The code of this Meassure.  # noqa: E501
        :type code: str
        :param fechamuestreo: The fechamuestreo of this Meassure.  # noqa: E501
        :type fechamuestreo: str
        :param unidad: The unidad of this Meassure.  # noqa: E501
        :type unidad: str
        :param tipo: The tipo of this Meassure.  # noqa: E501
        :type tipo: str
        :param medicion: The medicion of this Meassure.  # noqa: E501
        :type medicion: float
        """
        self.swagger_types = {
            'code': str,
            'fechamuestreo': str,
            'unidad': str,
            'tipo': str,
            'medicion': float
        }

        self.attribute_map = {
            'code': 'code',
            'fechamuestreo': 'fechamuestreo',
            'unidad': 'unidad',
            'tipo': 'tipo',
            'medicion': 'medicion'
        }

        self._code = code
        self._fechamuestreo = fechamuestreo
        self._unidad = unidad
        self._tipo = tipo
        self._medicion = medicion

    @classmethod
    def from_dict(cls, dikt) -> 'Meassure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Meassure of this Meassure.  # noqa: E501
        :rtype: Meassure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> str:
        """Gets the code of this Meassure.


        :return: The code of this Meassure.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code: str):
        """Sets the code of this Meassure.


        :param code: The code of this Meassure.
        :type code: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def fechamuestreo(self) -> str:
        """Gets the fechamuestreo of this Meassure.


        :return: The fechamuestreo of this Meassure.
        :rtype: str
        """
        return self._fechamuestreo

    @fechamuestreo.setter
    def fechamuestreo(self, fechamuestreo: str):
        """Sets the fechamuestreo of this Meassure.


        :param fechamuestreo: The fechamuestreo of this Meassure.
        :type fechamuestreo: str
        """
        if fechamuestreo is None:
            raise ValueError("Invalid value for `fechamuestreo`, must not be `None`")  # noqa: E501

        self._fechamuestreo = fechamuestreo

    @property
    def unidad(self) -> str:
        """Gets the unidad of this Meassure.


        :return: The unidad of this Meassure.
        :rtype: str
        """
        return self._unidad

    @unidad.setter
    def unidad(self, unidad: str):
        """Sets the unidad of this Meassure.


        :param unidad: The unidad of this Meassure.
        :type unidad: str
        """
        if unidad is None:
            raise ValueError("Invalid value for `unidad`, must not be `None`")  # noqa: E501

        self._unidad = unidad

    @property
    def tipo(self) -> str:
        """Gets the tipo of this Meassure.


        :return: The tipo of this Meassure.
        :rtype: str
        """
        return self._tipo

    @tipo.setter
    def tipo(self, tipo: str):
        """Sets the tipo of this Meassure.


        :param tipo: The tipo of this Meassure.
        :type tipo: str
        """
        if tipo is None:
            raise ValueError("Invalid value for `tipo`, must not be `None`")  # noqa: E501

        self._tipo = tipo

    @property
    def medicion(self) -> float:
        """Gets the medicion of this Meassure.


        :return: The medicion of this Meassure.
        :rtype: float
        """
        return self._medicion

    @medicion.setter
    def medicion(self, medicion: float):
        """Sets the medicion of this Meassure.


        :param medicion: The medicion of this Meassure.
        :type medicion: float
        """
        if medicion is None:
            raise ValueError("Invalid value for `medicion`, must not be `None`")  # noqa: E501

        self._medicion = medicion
